-- Wiz Issues Table
CREATE TABLE IF NOT EXISTS wiz_issues (
    id TEXT PRIMARY KEY,
    name TEXT,
    severity TEXT,
    status TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    due_at TIMESTAMP WITH TIME ZONE,
    status_changed_at TIMESTAMP WITH TIME ZONE,
    resolution_reason TEXT,
    control_id TEXT,
    entity_name TEXT,
    resource_id TEXT,
    resource_type TEXT,
    project_id TEXT,
    source_rule_id TEXT,
    source_rule_name TEXT,
    raw_data JSONB
);

-- Wiz Vulnerabilities Table
CREATE TABLE IF NOT EXISTS wiz_vulnerabilities (
    id TEXT PRIMARY KEY,
    finding_name TEXT,
    cve_id TEXT,
    severity TEXT,
    vendor_severity TEXT,
    cvss_score NUMERIC,
    epss_score NUMERIC,
    epss_percentile NUMERIC,
    has_exploit BOOLEAN,
    description TEXT,
    status TEXT,
    fixed_version TEXT,
    package_name TEXT,
    package_version TEXT,
    package_manager TEXT,
    first_detected_at TIMESTAMP WITH TIME ZONE,
    last_detected_at TIMESTAMP WITH TIME ZONE,
    resource_id TEXT,
    asset_name TEXT,
    project_id TEXT,
    asset_external_id TEXT,
    asset_subscription_id TEXT,
    asset_subscription_name TEXT,
    asset_subscription_external_id TEXT,
    asset_has_wide_internet_exposure BOOLEAN,
    asset_has_limited_internet_exposure BOOLEAN,
    asset_is_accessible_from_vpn BOOLEAN,
    asset_provider_unique_id TEXT,
    asset_resource_group TEXT,
    asset_ip_addresses TEXT[],
    raw_data JSONB
);

-- Wiz Inventory (Assets) Table
CREATE TABLE IF NOT EXISTS wiz_inventory (
    id TEXT PRIMARY KEY,
    name TEXT,
    type TEXT,
    native_type TEXT,
    external_id TEXT,
    provider TEXT,
    region TEXT,
    subscription_id TEXT,
    subscription_name TEXT,
    subscription_external_id TEXT,
    status TEXT,
    first_seen TIMESTAMP WITH TIME ZONE,
    last_seen TIMESTAMP WITH TIME ZONE,
    project_id TEXT,
    ip_addresses TEXT[],
    dns_names TEXT[],
    tags JSONB,
    has_public_ip BOOLEAN,
    raw_data JSONB
);

-- Tenable Assets Table
CREATE TABLE IF NOT EXISTS tenable_assets (
    id UUID PRIMARY KEY,
    hostname TEXT,
    fqdn TEXT,
    fqdns TEXT[],
    ipv4 TEXT,
    ipv4s TEXT[],
    ipv6 TEXT,
    ipv6s TEXT[],
    mac_address TEXT,
    mac_addresses TEXT[],
    netbios_name TEXT,
    netbios_names TEXT[],
    operating_systems TEXT[],
    system_types TEXT[],
    acr_score NUMERIC,
    exposure_score NUMERIC,
    agent_uuid UUID,
    bios_uuid TEXT,
    has_agent BOOLEAN,
    network_id TEXT,
    network_name TEXT,
    tags JSONB,
    sources JSONB,
    installed_software TEXT[],
    last_licensed_scan_date TIMESTAMP WITH TIME ZONE,
    last_authenticated_scan_date TIMESTAMP WITH TIME ZONE,
    aws_ec2_instance_id TEXT,
    aws_region TEXT,
    aws_availability_zone TEXT,
    aws_vpc_id TEXT,
    aws_owner_id TEXT,
    aws_ec2_instance_type TEXT,
    azure_vm_id TEXT,
    azure_resource_id TEXT,
    azure_subscription_id TEXT,
    azure_resource_group TEXT,
    azure_location TEXT,
    gcp_project_id TEXT,
    gcp_zone TEXT,
    gcp_instance_id TEXT,
    servicenow_sysid TEXT,
    ssh_fingerprint_sha256 TEXT[],
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    last_seen TIMESTAMP WITH TIME ZONE,
    raw_data JSONB
);

-- Tenable Findings (Vulnerabilities) Table
CREATE TABLE IF NOT EXISTS tenable_findings (
    id TEXT PRIMARY KEY,
    asset_id UUID,
    asset_hostname TEXT,
    asset_ipv4 TEXT,
    asset_fqdn TEXT,
    plugin_id INTEGER,
    plugin_name TEXT,
    plugin_family TEXT,
    plugin_synopsis TEXT,
    plugin_solution TEXT,
    severity TEXT,
    risk_factor TEXT,
    state TEXT,
    port INTEGER,
    protocol TEXT,
    cvss_score NUMERIC,
    cvss3_score NUMERIC,
    vpr_score NUMERIC,
    cve TEXT,
    cves TEXT[],
    exploit_available BOOLEAN,
    exploited_by_malware BOOLEAN,
    patch_publication_date TIMESTAMP WITH TIME ZONE,
    first_found TIMESTAMP WITH TIME ZONE,
    last_found TIMESTAMP WITH TIME ZONE,
    raw_data JSONB
);

-- Sync State Table for Resumable Syncs
CREATE TABLE IF NOT EXISTS sync_state (
    task_name TEXT PRIMARY KEY,
    last_cursor TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- CISA KEV (Known Exploited Vulnerabilities) Table
CREATE TABLE IF NOT EXISTS cisa_kev (
    cve_id TEXT PRIMARY KEY,
    vendor_project TEXT,
    product TEXT,
    vulnerability_name TEXT,
    date_added DATE,
    short_description TEXT,
    required_action TEXT,
    due_date DATE,
    known_ransomware_use TEXT,
    notes TEXT,
    cwes TEXT[],
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    raw_data JSONB
);

-- Tenable ASM (Attack Surface Management) Assets Table
CREATE TABLE IF NOT EXISTS tenable_asm_assets (
    id TEXT PRIMARY KEY,
    name TEXT,
    hostname TEXT,
    type TEXT,
    source TEXT,
    original TEXT,
    apex_domain TEXT,
    tags JSONB,
    technologies JSONB,
    first_seen TIMESTAMP WITH TIME ZONE,
    last_seen TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    address TEXT,
    ip_address TEXT,
    port INTEGER,
    protocol TEXT,
    service TEXT,
    open_ports TEXT[],
    all_services TEXT[],
    severity_ranking TEXT,
    asn TEXT,
    asn_number INTEGER,
    city TEXT,
    country TEXT,
    country_code TEXT,
    region TEXT,
    isp TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    is_cloud BOOLEAN,
    cloud_provider TEXT,
    registrar TEXT,
    domain_registrant TEXT,
    domain_created_at TEXT,
    domain_expires_at TEXT,
    ssl_grade TEXT,
    ssl_cert_expiry TEXT,
    http_title TEXT,
    http_server TEXT,
    raw_data JSONB
);

-- phpIPAM Assets Table (from CSV)
CREATE TABLE IF NOT EXISTS phpipam_assets (
    ip_address TEXT PRIMARY KEY,
    phpipam_id INTEGER,
    hostname TEXT,
    description TEXT,
    state TEXT,
    mac_address TEXT,
    owner TEXT,
    device TEXT,
    port TEXT,
    note TEXT,
    edit_date TIMESTAMP WITH TIME ZONE,
    is_gateway BOOLEAN,
    point_of_contact TEXT,
    subnet_description TEXT,
    subnet_owner TEXT,
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    raw_data JSONB
);
